version: '3'

services:
  postgres_core:
    image: postgres:latest
    container_name: postgres_core
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_core:/var/lib/postgresql/data

  postgres_auth:
    image: postgres:latest
    container_name: postgres_auth
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_auth:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  core:
    build:
      context: ./bookmytea_core
    container_name: core
    depends_on:
      - postgres_core
      - redis
    env_file:
      - bookmytea_core/app/.env

  auth:
    build:
      context: ./bookmytea_auth
    container_name: auth
    depends_on:
      - postgres_auth
      - redis
    env_file:
      - bookmytea_auth/app/.env

  integrations:
    build:
      context: ./bookmytea_integrations
    container_name: integrations
    depends_on:
      - core
      - auth
      - redis
    env_file:
      - bookmytea_integrations/app/.env
    restart: on-failure

  frontend:
    build:
      context: ./bookmytea_frontend
    container_name: frontend
    ports:
      - "8000:8000"
    depends_on:
      - core
      - auth
      - integrations
    env_file:
      - bookmytea_frontend/app/.env

volumes:
  postgres_core:
  postgres_auth:
  redis:
  minio: