name: Сборка образов

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Чекаут
      uses: actions/checkout@v2

    - name: Настройка Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Сборка и пуш микросервиса auth
      uses: docker/build-push-action@v2
      with:
        context: ./bookmytea_auth/
        push: true
        tags: registry.onmyneck.online/auth:latest

    - name: Сборка и пуш микросервиса core
      uses: docker/build-push-action@v2
      with:
        context: ./bookmytea_core/
        push: true
        tags: registry.onmyneck.online/core:latest

    - name: Сборка и пуш микросервиса frontend
      uses: docker/build-push-action@v2
      with:
        context: ./bookmytea_frontend/
        push: true
        tags: registry.onmyneck.online/frontend:latest

    - name: Сборка и пуш микросервиса integrations
      uses: docker/build-push-action@v2
      with:
        context: ./path/to/dockerfile4
        push: true
        tags: registry.onmyneck.online/integrations:latest